<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-05-30 at 12:58:57.
 */
require_once dirname(__FILE__) . '/../../src/cSolr.php';

class cSolrTest extends PHPUnit_Framework_TestCase {

    /**
     * @var cSolr
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new cSolr;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * Generated from @assert (1) == null.
     *
     * @covers cSolr::addOrderBy
     */
    public function testAddOrderBy() {
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers cSolr::read
     * @todo   Implement testRead().
     * @dataProvider commondata
     */
    public function testRead() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers cSolr::create
     * @todo   Implement testCreate().
     * @dataProvider commondata
     */
    public function testCreate() {
        // Remove the following lines when you implement this test.
        $this->assertEquals(12, $this->object->create());
    }

    /**
     * @covers cSolr::update
     * @todo   Implement testUpdate().
     * @dataProvider commondata
     */
    public function testUpdate() {

        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers cSolr::delete
     * @todo   Implement testDelete().
     * @dataProvider commondata
     */
    public function testDelete() {

        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers cSolr::addLimit
     * @todo   Implement testAddLimit().
     */
    public function testAddLimit() {

        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers cSolr::addOffset
     * @todo   Implement testAddOffset().
     */
    public function testAddOffset() {

        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers cSolr::addWhereCondition
     * @todo   Implement testAddWhereCondition().
     */
    public function testAddWhereCondition() {

        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers cSolr::commit
     * @todo   Implement testCommit().
     */
    public function testCommit() {

        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    function commondata() {

//Set 1
        $this->object->column['id'] = 100256584646464;
        $this->object->column['name'] = 'Test Record';
    }

}
